### ISSUE TITLE
Push the 0.6.0 gem?

### ISSUE THREAD

**Issue by JackDanger** [lfittl/pg_query#12]
I just switched off sql-parser to pg_query and it's perfect but I need the deparser. Is there anything blocking a 0.6.0 gem release that I could help with?

**Comment by lfittl** [comment]
For sure, I'm planning for the release this week :)

Ideally I'd like to get https://github.com/lfittl/pg_query/pull/10 by @mme in - but its not a blocker, so happy to already shoot out a stable version tonight if it helps.

**Comment by JackDanger** [comment]
Awesome :)

**Comment by mme** [comment]
@lfittl I might find time tomorrow morning to do it :)

**Comment by lfittl** [comment]
Thanks for your help - pushed 0.6! :guitar:
