### ISSUE TITLE
Problem when deparsing 'EXCEPT'

### ISSUE THREAD

**Issue by primeapple** [lfittl/pg_query#125]
Hi there,

I just found another bug in deparse. (Btw, @lfittl , i'm probably going to find some more, since I'm testing this a lot currently. Do you want me to continue submitting bugreports or should I stop to not fill your issues list up?)

This bug is when you use a query that contains the `EXCEPT` keyword and then try to deparse the query. This problem seems to be something deeper, since it does NOT throw an exception.

Example:
```ruby
PgQuery.parse("SELECT a FROM x EXCEPT SELECT a FROM Y").deparse
=> ""
PgQuery.parse("SELECT a FROM x UNION (SELECT a from Z EXCEPT SELECT a FROM Y)").deparse
=> "SELECT \"a\" FROM \"x\" UNION "
```

I hope you can trace this issue down quickly! Have a great time!

**Comment by herwinw** [comment]
> Btw, @lfittl , i'm probably going to find some more, since I'm testing this a lot currently. Do you want me to continue submitting bugreports or should I stop to not fill your issues list up?

I would say to just keep them coming. I'm pretty sure the deparse module is far from complete (there are a few PRs open to improve it).

**Comment by lfittl** [comment]
Fixed by https://github.com/lfittl/pg_query/commit/823155cec95a7e720633b2f498581b92a18722fb
