### ISSUE TITLE
Problem when deparsing Queries with UNION

### ISSUE THREAD

**Issue by primeapple** [lfittl/pg_query#129]
And another one:

"SELECT * FROM \"test\" UNION SELECT * FROM \"test2\""
We have the (quite stupid) query:
```sql
WITH test AS (SELECT * FROM student),
test2 AS (SELECT * FROM student)
SELECT * FROM test
UNION
SELECT * FROM test2
ORDER BY id DESC
```

When we parse and deparse this query we get something very very funny:
```sql
SELECT * FROM "test" UNION SELECT * FROM "test2"
```
Now this is amazing. It seems, that when you deparse something with UNION, you forget everything else (WITH, ORDER BY, probably HAVING, ...)

**Comment by lfittl** [comment]
Fixed by https://github.com/lfittl/pg_query/commit/823155cec95a7e720633b2f498581b92a18722fb
