### ISSUE TITLE
BUILD ERROR -- bundler not found

### ISSUE THREAD

**Issue by himanshu-pro** [lfittl/pg_query#141]
ERROR:
```
bundle install --jobs=3 --retry=3 --deployment
Traceback (most recent call last):
	4: from /home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
	3: from /home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
	2: from /home/travis/.rvm/gems/ruby-2.5.1/bin/bundle:23:in `<main>'
	1: from /home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
```
Please see for resolution https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html

**Comment by himanshu-pro** [comment]
@lfittl Please help..

**Comment by himanshu-pro** [comment]
Following PRs are encountering the issue..

https://github.com/lfittl/pg_query/pull/139
https://github.com/lfittl/pg_query/pull/140
https://github.com/lfittl/pg_query/pull/143

Please tell me if this is an issue on my end.. Thanks..

**Comment by lfittl** [comment]
@himanshu-pro Could you rebase to the latest master?

This seems to have been an issue with the specific Ruby version. Thanks!

**Comment by himanshu-pro** [comment]
@lfittl Thanks a lot.. Have made the appropriate changes..
