### ISSUE TITLE
can support parse "merge into "?

### ISSUE THREAD

**Issue by alex-jh-jiang** [lfittl/pg_query#159]
hi, i'm very interest in pg_query, my rdbms is vertica, but below parsed failed, help!!!

irb(main):551:0> PgQuery.parse("MERGE INTO APDSP.LCP_SYS_USER TAR
irb(main):552:1" USING SFULL.S14_KM_STAFFINFO SRC ON TAR.USER_ID = SRC.USERID
irb(main):553:1" and (SRC.VC_STATUS is null or SRC.VC_STATUS<>'leave')
irb(main):554:1" WHEN MATCHED THEN UPDATE SET USER_NAME = OPERATORNAME,DEPARTMENTID =ORGCODE,OPERATOR_ID=OPERATORID
irb(main):555:1" WHEN NOT MATCHED THEN
irb(main):556:1" INSERT (USER_ID,USER_NAME, PWD,DEPARTMENTID,OPERATOR_ID)
irb(main):557:1" VALUES (USERID,OPERATORNAME,'userPass123',ORGCODE,OPERATORID)")
Traceback (most recent call last):
        4: from /usr/bin/irb:11:in `<main>'
        3: from (irb):551
        2: from /usr/local/share/gems/gems/pg_query-1.1.0/lib/pg_query/parse.rb:5:in `parse'
        1: from /usr/local/share/gems/gems/pg_query-1.1.0/lib/pg_query/parse.rb:5:in `_raw_parse'
PgQuery::ParseError (syntax error at or near "MERGE" (scan.l:1121))

**Comment by lfittl** [comment]
Hi @alex-jh-jiang We only support official PostgreSQL syntax, since this is built on the Postgres parser.

Therefore we unfortunately won't add support for `MERGE INTO` and other non-Postgres syntax. It would lead to all kinds of complications as we update the library for new Postgres versions.
