### ISSUE TITLE
PgQuery::ParseError with `normalize` and parameterized intervals

### ISSUE THREAD

**Issue by ankane** [lfittl/pg_query#169]
Hey @lfittl, thanks again for this great project!

`PgQuery.normalize` throws `syntax error at or near "$1" (scan.l:1121) (PgQuery::ParseError)` for queries have already been parameterized that use `interval`. It doesn't throw an error for other queries that have been parameterized. I discovered this while running queries from `pg_stat_statements` through `normalize` - most succeeded but ones with `interval` failed.

Short script to reproduce:

```ruby
require "pg_query"

p PgQuery.normalize("select 1") # success
p PgQuery.normalize("select $1") # success
p PgQuery.normalize("select interval '1 day'") # success
p PgQuery.normalize("select interval $1") # error
```

Version: 1.2.0 (latest release)

**Comment by lfittl** [comment]
Thanks for the report @ankane!

Ultimately this is a problem with the Postgres parser:

```
db=# PREPARE x AS select interval $1;
ERROR:  syntax error at or near "$1"
LINE 1: PREPARE x AS select interval $1;
                                     ^
db=# PREPARE x AS select $1::interval;
PREPARE
```

You could consider doing a simple regexp to fix up the query text before passing it to the normalize function, as a workaround.

The proper solution here would be to fix the pg_stat_statements handling upstream - I'd rather try to avoid patching the parser in libpg_query for this.

**Comment by ankane** [comment]
Hey @lfittl, thanks for crazy fast response, root cause, and workaround! Will close this out.
