### ISSUE TITLE
Support for Ruby 3

### ISSUE THREAD

**Issue by ankane** [lfittl/pg_query#179]
Hi @lfittl, thanks for this awesome project! With the latest version, installation fails for Ruby 3 with:

```text
extconf.rb:15:in `initialize': No such file or directory @ rb_sysopen - https://codeload.github.com/lfittl/libpg_query/tar.gz/10-1.0.1 (Errno::ENOENT)
	from extconf.rb:15:in `open'
	from extconf.rb:15:in `block in <main>'
	from extconf.rb:14:in `open'
	from extconf.rb:14:in `<main>'
```

Looking at `extconf.rb`, I think it needs to use `URI.open` instead of `open` based on the Ruby 2.7 deprecation warning (`warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open`).

**Comment by stanhu** [comment]
I think this may be covered by https://github.com/lfittl/pg_query/pull/178?

@lfittl Perhaps this warrants a new release now?

**Comment by lfittl** [comment]
@ankane @stanhu Yup, agreed, thats a good reason for a release - `1.3.0` has been released now & pushed to Rubygems.

Happy holidays! 🎆

**Comment by ankane** [comment]
Awesome, thanks @lfittl! Happy holidays to you, too.

**Comment by ankane** [comment]
Just fyi, it looks like `URI.open` is private in Ruby < 2.5, so it may make sense to add `s.required_ruby_version = ">= 2.5"` to the gemspec.

**Comment by lfittl** [comment]
@ankane Yeah, I noticed that earlier. Given that Ruby < 2.5 is EOL, I think its probably fine to not handle that? (unless you see a benefit in adding it to the gemspec?)

**Comment by ankane** [comment]
If it was part of the 1.3.0 release, Bundler would install 1.2.0 on Ruby 2.4 instead of failing with 1.3.0, so may just be something to keep in mind for next time.
