### ISSUE TITLE
distinct clause 

### ISSUE THREAD

**Issue by carolfly86** [lfittl/pg_query#37]
Hi,
The distinct clause seems a little off to me. Not sure if this is an issue or this is by design. I would think it should be true if there's distinct key word, but it's [nil].
pp PgQuery.parse("select distinct a from t")
#<PgQuery:0x007fa1ca036f60
 @parsetree=
  [{"SELECT"=>
     {"distinctClause"=>[nil],
      "intoClause"=>nil,
      "targetList"=>
       [{"RESTARGET"=>
          {"name"=>nil,
           "indirection"=>nil,
           "val"=>{"COLUMNREF"=>{"fields"=>["a"], "location"=>16}},
           "location"=>16}}],
      "fromClause"=>
       [{"RANGEVAR"=>
          {"schemaname"=>nil,
           "relname"=>"t",
           "inhOpt"=>2,
           "relpersistence"=>"p",
           "alias"=>nil,
           "location"=>23}}],
      "whereClause"=>nil,
      "groupClause"=>nil,
      "havingClause"=>nil,
      "windowClause"=>nil,
      "valuesLists"=>nil,
      "sortClause"=>nil,
      "limitOffset"=>nil,
      "limitCount"=>nil,
      "lockingClause"=>nil,
      "withClause"=>nil,
      "op"=>0,
      "all"=>false,
      "larg"=>nil,
      "rarg"=>nil}}]

**Comment by lfittl** [comment]
@carolfly86 Thanks for the report - we're using Postgres' own parser here, and I think this is correct.

From reading the source in parsenodes.h:

```
	List	   *distinctClause; /* NULL, list of DISTINCT ON exprs, or
								 * lcons(NIL,NIL) for all (SELECT DISTINCT) */
```

(https://github.com/postgres/postgres/blob/master/src/include/nodes/parsenodes.h#L1280)

I think we're translating `lcons(NIL,NIL)` as `[nil]` here - I think this is safe to check for in your own code.

If there is a `DISTINCT ON(x)` clause it will look like `"distinctClause"=>[{"COLUMNREF"=>{"fields"=>["x"], "location"=>19}}]`.

And if there is no `DISTINCT` clause it will simply be `nil` without the wrapping array.

At this point we're not doing much more to the parse tree apart from translating it into JSON (and then a Ruby hash), so there is no quick way to improve this - I certainly agree that checking for `[nil]` is a bit odd.

**Comment by carolfly86** [comment]
Thanks for you response. It's a great tool for me :+1:

**Comment by lfittl** [comment]
Happy to hear - feel free to ask questions like this any time, feedback is also very welcome :+1:
