### ISSUE TITLE
Possible problem with A_CONST in version 0.9.1

### ISSUE THREAD

**Issue by yoid2000** [lfittl/pg_query#47]
Hi guys...love this gem!

I encountered a problem when I upgraded from 0.7.2 to 0.9.1.

Specifically, the val field within the A_CONST structure is getting set to null when it should not be.

To give an example, I give it this SQL (snippet):

```
SELECT concat(p.firstname, ' ', p.lastname) AS a
```

The produced JSON is this:

```
"SELECT": {
              "targetList": [
                {
                  "RESTARGET": {
                    "name": "a",
                    "val": {
                      "FUNCCALL": {
                        "funcname": [
                          "concat"
                        ],
                        "args": [
                          {
                            "COLUMNREF": {
                              "fields": [
                                "p",
                                "firstname"
                              ],
                              "location": 79
                            }
                          },
                          {
                            "A_CONST": {
                              "val": null,
                              "location": 92,
                              "type": "integer"
                            }
                          },
                          {
                            "COLUMNREF": {
                              "fields": [
                                "p",
                                "lastname"
                              ],
                              "location": 97
                            }
                          }
                        ],
                        "location": 72
                      }
                    },
                    "location": 72
                  }
                }
              ],
```

As you can see, the "val" field within "A_CONST" is null.  Also incorrect, the "type" in set as "integer".  

When run in 0.7.2, the same A_CONST produces this:

```
                         {
                            "A_CONST": {
                              "type": "string",
                              "val": " ",
                              "location": 89
                            }
                          },
```
 (ignore the location...other parts of the SQL differ, but I don't think that effects the output).

The problem is not limited to strings containing whitespace.  For instance, I had the same problem with a snippet of SQL like this:

```
WHERE gender = 'M'
```

I've since upgraded our system (or, downgraded as the case may be), so can't immediately reproduce the problem.  But let me know if you need me to.  Also please let me know what other info you might require about my system setup.

**Comment by lfittl** [comment]
@yoid2000 Ah, thats indeed a bug in the `.parsetree` method - thanks for the report!

As a sidenote, 0.9 and newer have a new parse tree format, that matches PostgreSQL's internal format more closely. When you have the time I'd recommend transitioning it - you can access the new method with the `.tree` method on the query object.

Btw, happy that you're using the library - if you can share what you're working on (if its publicly available) I'd be happy to add it to the README in "Products, tools and libraries built on pg_query" :)

**Comment by yoid2000** [comment]
@lfittl 

Ok, will consider moving to the new format at some point, but we have a fair amount of code that works with 0.7, so don't want to touch it just now.

The project is some anonymized database research we are doing.  The nature of the anonymization is such that we need to place certain restrictions on, and make certain changes to the SQL generated by the analyst.  This is written in perl, so we get a json structure from you, turn it into a perl structure, parse that, and then use it to generate modified queries.

**Comment by lfittl** [comment]
@yoid2000 Nice, thats a fascinating use case for pg_query - happy its useful!

In case you encounter any other incompatibilities feel free to open an issue anytime, my goal is to keep the translation layer well-maintained since there are a few projects that depend on the old format.

**Comment by yoid2000** [comment]
Quick question:  Is there a way to get a reasonable parsing error 
message back from pq_query?  In other words, something that gives an 
indication of what is wrong with the SQL syntax.  I scanned your 
documentation but didn't find anything.

Thanks,

PF

**Comment by lfittl** [comment]
@yoid2000 Unfortunately the error message can be a bit cryptic at times. The one you get back is the `ParseError`, which gets thrown when the SQL can't be parsed.

It'll also have `.location` accessible, to indicate where in the input string the error lies (or where PostgreSQL thinks it is).

A few examples:

```
"SELEC" => syntax error at or near "SELEC"
"SELECT * FROM 123" => syntax error at or near "123"
"SELECT (" => syntax error at the end of input
"SELECT '" => unterminated quoted string at or near "'"
```

Does that help / answer the question?

**Comment by yoid2000** [comment]
Finally got round to this.  My problem was that I wasn't catching the 
ParseError at all.  But now I am and it works fine, so thanks for your 
response.

PF

**Comment by lfittl** [comment]
@yoid2000 That makes sense - happy to hear it works for you now :)
