### ISSUE TITLE
"Between" and "In" operator doe not have "AEXPR" ?

### ISSUE THREAD

**Issue by carolfly86** [lfittl/pg_query#66]
Hi, 
I'm not sure if this is a feature or bug. I noticed that for "Between" and "IN" operators in where clause the parse tree does not contain the "AEXPR" key. Whereas for "=" operator there's  the 'AEXPR' key
For example:
```>> q='select id from t where id between 3 and 4'
=> "select id from t where id between 3 and 4"
>> pp PgQuery.parse(q).parsetree[0]
{"SELECT"=>
  {"targetList"=>
    [{"RESTARGET"=>
       {"val"=>{"COLUMNREF"=>{"fields"=>["id"], "location"=>7}},
        "location"=>7}}],
   "fromClause"=>
    [{"RANGEVAR"=>
       {"relname"=>"t", "inhOpt"=>2, "relpersistence"=>"p", "location"=>15}}],
   "whereClause"=>
    {nil=>
      {"name"=>["BETWEEN"],
       "lexpr"=>{"COLUMNREF"=>{"fields"=>["id"], "location"=>23}},
       "rexpr"=>
        [{"A_CONST"=>{"val"=>3, "location"=>34, "type"=>"integer"}},
         {"A_CONST"=>{"val"=>4, "location"=>40, "type"=>"integer"}}],
       "location"=>26}},
   "op"=>0}}



>> q='select id from t where id =3'
=> "select id from t where id =3"
>> pp PgQuery.parse(q).parsetree[0]
{"SELECT"=>
  {"targetList"=>
    [{"RESTARGET"=>
       {"val"=>{"COLUMNREF"=>{"fields"=>["id"], "location"=>7}},
        "location"=>7}}],
   "fromClause"=>
    [{"RANGEVAR"=>
       {"relname"=>"t", "inhOpt"=>2, "relpersistence"=>"p", "location"=>15}}],
   "whereClause"=>
    {"AEXPR"=>
      {"name"=>["="],
       "lexpr"=>{"COLUMNREF"=>{"fields"=>["id"], "location"=>23}},
       "rexpr"=>{"A_CONST"=>{"val"=>3, "location"=>27, "type"=>"integer"}},
       "location"=>26}},
   "op"=>0}}

**Comment by lfittl** [comment]
@carolfly86 Thanks for the report - that is indeed a bug, and I just fixed it in https://github.com/lfittl/pg_query/commit/bd1aba2fcbd1774a6b66319423f2f1be8d66410b

I will probably stamp a new release soon, but if helpful I can also make a quick bugfix release just for this - let me know if that'd be helpful.

Also just as a note, if you are developing something new: `.parsetree` is the legacy and deprecated method to access the tree. There is an updated format under `.tree` that matches what we get from Postgres / libpg_query itself, and I would recommend using that if possible.

**Comment by carolfly86** [comment]
Thanks @lfittl I can wait for the new release.

**Comment by lfittl** [comment]
@carolfly86 Release 0.13.2 now which contains this fix - thanks again for reporting!

**Comment by carolfly86** [comment]
thanks for fixing it!
