### ISSUE TITLE
Tables in subselects in joins don't seem to be detected properly

### ISSUE THREAD

**Issue by seanmdick** [lfittl/pg_query#67]
I found a mind-bendy little corner case.
```
> query = PgQuery.parse('select foo.*
  from foo
  join ( select * from bar ) b
  on b.baz = foo.quux')
> query.tables
  ['foo']
```
I'd expect this to return `['foo', 'bar']` PR incoming to fix it. Thanks for compiling so much of this already.

**Comment by lfittl** [comment]
Fixed via https://github.com/lfittl/pg_query/commit/4f75f2da1a2a807e612a6d95eb2cfd52808f8efd

Thanks!
