### ISSUE TITLE
Sort order dependency on truncations in #truncate

### ISSUE THREAD

**Issue by sshao** [lfittl/pg_query#8]
Hello,

This may wind up being more of a question than an actual issue:

# Context

I was experimenting with making pg_query ruby 1.8.7-compatible for a legacy project. After making some syntax changes, I managed to get all specs passing on 1.8.7 save for [PgQuery#truncate omits target list](https://github.com/lfittl/pg_query/blob/b6cd395afc3ac097cbdd2401e88d7d70fdb2ec9f/spec/lib/truncate_spec.rb#L4-L7), which [sometimes failed, and sometimes passed](https://gist.github.com/sshao/24f8a5f72f3f3c6c99b7). 

I dug down into a little and it seemed to be due to the order of the [`truncations` array in #truncate](https://github.com/lfittl/pg_query/blob/b6cd395afc3ac097cbdd2401e88d7d70fdb2ec9f/lib/pg_query/truncate.rb#L12): 

# Reproducing

Doesn't require ruby-1.8.7. 

* In the spec linked above, `truncations` winds up being an array of 2 elements: 
  * `#<struct PgQuery::PossibleTruncation location=["SELECT", "targetList"], node_type="targetList", length=16, is_array=true>`
  * `#<struct PgQuery::PossibleTruncation location=["SELECT", "whereClause"], node_type="whereClause", length=11, is_array=false>`
* In ruby 2.2.x on the current master branch of pg_query, the order of `truncations` is always the same. The truncation with length 16 is always the first element in the array.
* However, if we switch the order of the array around -- such that the truncation with length 11 is first -- the spec fails consistently:

```diff
[master] ~/devel/pg_query git diff
diff --git a/lib/pg_query/truncate.rb b/lib/pg_query/truncate.rb
index 6ea17fb..c5d829a 100644
--- a/lib/pg_query/truncate.rb
+++ b/lib/pg_query/truncate.rb
@@ -10,6 +10,7 @@ class PgQuery
     return output if output.size <= max_length
 
     truncations = find_possible_truncations
+    truncations.sort_by!(&:length)
 
     # TODO: Sort by most promising truncation
 ```
```shell
$ ~/devel/pg_query ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
$ ~/devel/pg_query bundle exec rspec spec -e 'PgQuery#truncate omits target list'
Run options: include {:full_description=>/PgQuery\#truncate\ omits\ target\ list/}
F

Failures:

  1) PgQuery#truncate omits target list
     Failure/Error: expect(described_class.parse(query).truncate(40)).to eq 'SELECT ... FROM xyz WHERE a = b'
       
       expected: "SELECT ... FROM xyz WHERE a = b"
            got: "SELECT ... FROM xyz WHERE ..."
       
       (compared using ==)
     # ./spec/lib/truncate_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 0.00487 seconds (files took 0.22303 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/lib/truncate_spec.rb:4 # PgQuery#truncate omits target list
```

Is this dependency on sort-order expected? Is the `truncations` array expected to be in a certain order (descending?)

**Comment by lfittl** [comment]
Thanks for the detailed write-up!

This code is a fairly recent addition (< 1 week old), and you're definitely right, the sort order there is not stable enough.

I'll see that I can fix this issue and update you when its taken care of.

That said, I'm surprised that Ruby 1.8 works (i.e. we're not using any 1.9 patterns by accident) - is there no way for you to upgrade to a newer Ruby version for that project?

**Comment by sshao** [comment]
No problem, thanks for the quick response! 

Re: upgrading, unfortunately not at the moment. But there weren't [too many changes needed to make pg_query build & pass specs on 1.8.7](https://github.com/lfittl/pg_query/compare/master...sshao:187_compatible) (ignoring the fact that rubocop had to be nixed due to a dependency issue that I haven't looked into yet). Would you be interested in a 1.8.7-compatible PR?

**Comment by lfittl** [comment]
Re: 1.8 compatibility, I'm not really sure to be honest.

It looks like its not too many changes, but it restricts what features we can use (and Ruby 1.8 has been end of life for some time now).

However, if you can get rubocop to work, I'm open to merging your changes in - although we might start using 1.9 features at some future point again.
