### ISSUE TITLE
CASE .... is incorrectly deparsed

### ISSUE THREAD

**Issue by depesz** [lfittl/pg_query#81]
There is a syntax like:

`case x when 1 then ... when 2 then ... end`

But current pg_query doesn't seem to deparse it correctly:

    puts PgQuery.parse( "SELECT CASE relkind WHEN 'r' THEN 'TABLE' when 'i' THEN 'INDEX' ELSE 'STH-ELSE' END as type FROM pg_class" ).deparse                                                                                                                                    
    SELECT CASE WHEN 'r' THEN 'TABLE' WHEN 'i' THEN 'INDEX' ELSE 'STH-ELSE' END AS type FROM "pg_class"

Please note the missing "relkind"

**Comment by depesz** [comment]
As far as I can tell, changing:

    def deparse_case(node)
      output = ['CASE']
      output += node['args'].map { |arg| deparse_item(arg) }
      if node['defresult']
        output << 'ELSE'
        output << deparse_item(node['defresult'])
      end
      output << 'END'
      output.join(' ')
    end

to

    def deparse_case(node)
      output = ['CASE']
      output << beautify_item(node['arg']) if node['arg']
      output += node['args'].map { |arg| beautify_item(arg) }
      if node['defresult']
        output << 'ELSE'
        output << beautify_item(node['defresult'])
      end
      output << 'END'
      output.join(' ')
    end

fixes the problem.

**Comment by lfittl** [comment]
@depesz Good catch - do you want to make a PR (plus test case) to fix?

The previous PRs should give a good example of how to write the test, it shouldn't be too much effort. That said, happy to fix this myself if you prefer :)

**Comment by lfittl** [comment]
@depesz Actually I just looked through the past PRs - I believe https://github.com/lfittl/pg_query/pull/78 fixes this, but hasn't been released yet.

Can you confirm whether thats the same case? Thanks :)

**Comment by depesz** [comment]
Yeah, sorry about that, was just checking released version.

**Comment by lfittl** [comment]
@depesz No worries, my bad for not making a new release - released now as `1.0.2`
