### ISSUE TITLE
(de?)parse fails

### ISSUE THREAD

**Issue by benchub** [lfittl/pg_query#86]
`print PgQuery.parse("update foo set a=?, b=?").deparse`

drops the comma, resulting in invalid sql

**Comment by lfittl** [comment]
@benchub Thanks for opening the issues regarding deparsing!

Your help would be very welcome in fixing these, the logic is in https://github.com/lfittl/pg_query/blob/master/lib/pg_query/deparse.rb and shouldn't be too hard to understand. We should also make sure to add tests for each of these cases, so it doesn't regress in a future Postgres version.

**Comment by benchub** [comment]
To be honest I was hoping to see how you fixed them while I got the rest of my stuff in order. :) And what I really need is to figure out how to do it all the go library, anyway. Which, doesn't look to be hard… just drudgery.
